/* header file generated by Kernel Tuner, do not modify by hand */
#pragma once
#ifndef kernel_tuner /* only use these when not tuning */


#ifdef TARGET_GeForce_GTX_TITAN_X
#define block_size_x 16
#define block_size_y 8

#else /* default configuration */
#define block_size_x 16
#define block_size_y 8
#endif /* GPU TARGETS */

#endif /* kernel_tuner */
